### ISSUE TITLE
Invalid xcconfig configuration in SDWebImageWebPCoder.podspec:

### ISSUE THREAD

**Issue by pepsikirk** [SDWebImage/SDWebImageWebPCoder#106]
Invalid xcconfig configuration in SDWebImageWebPCoder.podspec:

'USER_HEADER_SEARCH_PATHS' => '$(inherited) $(SRCROOT)/libwebp/src'

This is actually invalid because the directory $(SRCROOT)/libwebp/src does not exist. It can be removed.

**Comment by dreampiggy** [comment]
seems libwebp sourcode folder structure changes

**Comment by pepsikirk** [comment]
> seems libwebp source code folder structure changes

$(SRCROOT) is actually the project root directory. The final result leading to the project is as shown in the following figure:

![image](https://github.com/SDWebImage/SDWebImageWebPCoder/assets/7042430/ce04758f-a83e-43ee-b911-9656c61ae14f)

Therefore, the configuration is actually meaningless.

**Comment by dreampiggy** [comment]
SRCROOT is Pod.xcodeproj

If you enable `multiple_pods_project`, it will become `libwebp.xcodeproj`

**Comment by dreampiggy** [comment]
Seem type, this `SRCROOT` should be `PODS_ROOT`
