### ISSUE TITLE
Privacy Manifest Support

### ISSUE THREAD

**Issue by vadzimkaronchyk** [SDWebImage/SDWebImageWebPCoder#108]
Basically, my issue duplicates [this one](https://github.com/SDWebImage/SDWebImageWebPCoder/issues/93). But the thing is, both SDWebImageWebPCoder and SDWebImage can be used in the same project. In this case, I can't just upgrade SDWebImage to the latest version and use the current version of SDWebImageWebPCoder, because there is a problem when finding compatible versions pod "SDWebImage/Core". Could you please help with that?

**Comment by VadzimPlato** [comment]
I've solved my issue. It can be closed.
