### ISSUE TITLE
Call to undeclared function 'SD_LOG'; ISO C99 and later do not support implicit function declarations

### ISSUE THREAD

**Issue by Jack-Rain** [SDWebImage/SDWebImageWebPCoder#112]
When I use "pod 'SDWebImageWebPCoder', :path=> '/Users/xxx/SDWebImageWebPCoder-master'" to point SDWebImageWebPCoder to a local file, I get the error "Call to undeclared function 'SD_LOG'; ISO C99 and later do not support implicit function declarations" during compilation.

**Comment by dreampiggy** [comment]
Upgrade to the latest version, I think this already been fixed. This macro exists in `SDInternal.h`, which the private search path pointed to

**Comment by Jack-Rain** [comment]
> Upgrade to the latest version, I think this already been fixed. This macro exists in `SDInternalMacros.h`, which the private search path pointed to
> 
> https://github.com/SDWebImage/SDWebImageWebPCoder/blob/master/SDWebImageWebPCoder/Private/SDInternalMacros.h

it is already the latest version

**Comment by dreampiggy** [comment]
You can check your environment, open in Xcode project and jump into `SDImageWebPCoder.m`, go to 

```
#import "SDInteralMacros.h"
```

Command + Click this line, where that `SDInternalMacros.h` pointed to ? Is that a broken file or something inside `SDWebImage` (not `SDWebImageWebPCoder` ?)

**Comment by Jack-Rain** [comment]
> You can check your environment, open in Xcode project and jump into `SDImageWebPCoder.m`, go to
> 
> ```
> #import "SDInteralMacros.h"
> ```
> 
> Command + Click this line, where that `SDInternalMacros.h` pointed to ? Is that a broken file or something inside `SDWebImage` (not `SDWebImageWebPCoder` ?)

It points to SDWebImageWebPCoder where the definition of SD_LOG is not included.

**Comment by Jack-Rain** [comment]
[SDTest.zip](https://github.com/user-attachments/files/16411561/SDTest.zip)
This demo can reproduce the issue

**Comment by dreampiggy** [comment]
Is this because the `SDInternalMacros.h` copied from SDWebImage Core is not updated ?

**Comment by dreampiggy** [comment]
I mean, where this `SD_LOG` is used ? SDWebImageWebPCoder itself seems does not have **any call** to this `SD_LOG` macro

**Comment by dreampiggy** [comment]
I guess it's bug or issue on CocoaPods.

These 2 repo contains different path for the same file name `SDInternalMacros.h`, but it should not cause issue, if exists, it's Package Manager's bug (CocoaPods)

**Comment by Jack-Rain** [comment]
> I mean, where this `SD_LOG` is used ? SDWebImageWebPCoder itself seems does not have **any call** to this `SD_LOG` macro
![image](https://github.com/user-attachments/assets/119cc9f6-f0ad-4430-918f-1888cdf7e98f)

**Comment by Jack-Rain** [comment]
> I guess it's bug or issue on CocoaPods.
> 
> These 2 repo contains different path for the same file name `SDInternalMacros.h`, but it should not cause issue, if exists, it's Package Manager's bug (CocoaPods)
maybe

**Comment by Jack-Rain** [comment]
> I guess it's bug or issue on CocoaPods.
> 
> These 2 repo contains different path for the same file name `SDInternalMacros.h`, but it should not cause issue, if exists, it's Package Manager's bug (CocoaPods)

maybe

**Comment by dreampiggy** [comment]
For local development, avoid the default configuration and always use

`install! 'cocoapods', :generate_multiple_pod_projects => true`
