### ISSUE TITLE
SDWebImageWebPCoder is not working

### ISSUE THREAD

**Issue by nicatguliyev** [SDWebImage/SDWebImageWebPCoder#19]
i have installed SDWebImageWebPCoder library. And I used
                           let WebCoder = SDImageWebPCoder.shared
                            SDImageCodersManager.shared.addCoder(WebCoder)
                            
                            let urlString = URL(string: x)
                            self.myImage.sd_setImage(with: urlString)

But webp image is not set in UiImageView

**Comment by kinarobin** [comment]
@nicatguliyev What the way you use `SDWebImageWebPCoder` in your project: 
 CocoaPods ?
 Carthage ?
manual install (build-only or embed Xcode Project) ?

**Comment by kinarobin** [comment]
You can add a breakpoint in `SDImageCodersManager` class to see whether there have a `webpCoder` to decode image ?
```ruby
- (UIImage *)decodedImageWithData:(NSData *)data options:(nullable SDImageCoderOptions *)options {
    if (!data) {
        return nil;
    }
    UIImage *image;
    NSArray<id<SDImageCoder>> *coders = self.coders;
    for (id<SDImageCoder> coder in coders.reverseObjectEnumerator) {
        if ([coder canDecodeFromData:data]) {
            image = [coder decodedImageWithData:data options:options];
            break;
        }
    }
    
    return image;
}

**Comment by dreampiggy** [comment]
> But webp image is not set in UiImageView

Did server response the valid WebP data ?

You can try to  set a breakpoint at the `URLSession:didCompleteWithError:` and read the image data.

**Comment by nicatguliyev** [comment]
> > But webp image is not set in UiImageView
> 
> Did server response the valid WebP data ?
> 
> You can try to set a breakpoint at the `URLSession:didCompleteWithError:` and read the image data. You can also save it to your disk and open in Chrome to see whether it can be rendered or not.
> 
> ```
> // using lldb
> po self.imageData
> expr [self.imageData writeToFile:@"/tmp/a.webp" atomically:YES];
> ```

Server reponse the valid Webp data

**Comment by nicatguliyev** [comment]
> @nicatguliyev What the way you use `SDWebImageWebPCoder` in your project:
> CocoaPods ?
> Carthage ?
> manual install (build-only or embed Xcode Project) ?

I installed via cocapods

**Comment by kinarobin** [comment]
Could you show some image urls to debug?

**Comment by nicatguliyev** [comment]
> Could you show some image urls to debug?

http://46.101.38.248/storage/posts/June2019/6rTPGNHXV8wjwAJ1vYZq.webp

**Comment by kinarobin** [comment]
@nicatguliyev Using this image url test in SDWebImage demo , It display normal. 
So you should check is there a issue with the way you use it?

![截屏2019-06-28上午10 56 46](https://user-images.githubusercontent.com/29303030/60313941-71cccc00-9993-11e9-9dd8-73aefeeef775.png)

**Comment by dreampiggy** [comment]
@nicatguliyev Could you please provide a re-producable demo, for use to investigate.

We can not provide any fix for this if we can not reproduce the issue.

**Comment by jerrin15** [comment]
i have the same issue i could not load my webp images from my server, the sample imageurl in this demo works but my own does not. My image loads without issue on the browser.
