### ISSUE TITLE
Feature Request: Supports webp animated image thumb decoding.

### ISSUE THREAD

**Issue by kinarobin** [SDWebImage/SDWebImageWebPCoder#21]
Normally, it should be the company's server to scale down the webp decoding. At present, it can decode the different size animated webp image with the company's server.

But for some historical reasons, the company's server can not scale down the long year ago webp animated image, which leads to the client's  waste too much memory space, so I hope this library can support the thumb decoding without the full pixel allocation on RAM.

Thanks

**Comment by dreampiggy** [comment]
Supported in v0.6.1 version. Close
