### ISSUE TITLE
Add Coder in SDWebImage SPM installation?

### ISSUE THREAD

**Issue by kunalverma25** [SDWebImage/SDWebImageWebPCoder#27]
There are no steps to include coders in SPM installation on SDWebImage.

**Comment by dreampiggy** [comment]
Not supported yet. Depends : https://github.com/SDWebImage/libwebp-Xcode/pull/3

**Comment by dreampiggy** [comment]
@kunalverma25 Try to use v0.3.0, which support SwiftPM. (The dependency libwebp use the v1.1.0-rc2+)
