### ISSUE TITLE
How to decode Image with quality option?

### ISSUE THREAD

**Issue by tanphamanhh** [SDWebImage/SDWebImageWebPCoder#34]
Im using `SDWebImageWebPCoder, '0.5.0'` for decode webp image.
Im using a unique queue `let queue =  DispatchQueue(label: "webp.decoder")` only for webp decode.
Is there any option to decode image with selection quality and keep the origin image size (like libwebpjs)?

**Comment by dreampiggy** [comment]
Decode does not have anything quality.

This is only applies to **Encoding**. When encoding you can choose lossy encoding algorithm and have a quality arg.

I guess what you want it's the thumbnail decoding. Check the readme again, there are already APIs and guide to use it.

**Comment by tanphamanhh** [comment]
Thanks for your answer,
I am wondering how can I improve the decoding progress because I decode multiple file at the same time.

**Comment by dreampiggy** [comment]
> Thanks for your answer,
> I'm wondering how can I improve the decoding progress because I decode multiple files at the same time. Maybe something like multi thread decoding?

libwebp's multi-thread feature is already turned on.

If you decode multiple files into single global queue, it's useless. The decoder are all thread-safe.

**Comment by dreampiggy** [comment]
You can also use the advanced webp codec options. See release changelog of [0.8.0](https://github.com/SDWebImage/SDWebImageWebPCoder/releases/tag/0.8.0) and updated README.
