### ISSUE TITLE
App crash when using Progressive Load with slow network 

### ISSUE THREAD

**Issue by JT501** [SDWebImage/SDWebImageWebPCoder#40]
It is fine when using fast network, but it will throw exception ``EXC_BAD_ACCESS`` when using slow network especially loading larger files (>1MB).
I turn off Progressive Load, it goes fine. 

I can reproduce this issue in demo project. 
I am using the latest SDWebImage + WebPCoder.

Best Regards.

**Comment by dreampiggy** [comment]
Maybe this is because the new progressive animated webp support. Can you provide the sample URL, and how slow your network is (So that I can use Charles to simulate this case).

**Comment by JT501** [comment]
Hi @dreampiggy 
You may use this sample (~4MB): https://img.co-fire.com/mention-la-local/l/NtUT9VZ0oxPpjG0TQvRPB19Ru5BzpYGNbF4VFyBb.webp

I use iPhone Network Link Conditioner ``3G`` preset to simulate, which should be around 780Kbps bandwidth.

SDWebImage version: 5.7.2
SDWebImageWebPCoder version: 0.6.0

Thx.

**Comment by dreampiggy** [comment]
Hi. I came back.

Seems this case is a little hard to reproduce.

I use the SDWebImageWebPCoder demo and use `progressLoad` on `SDAnimatedImageView`, use Charles to simulate 780Kbps bandwith, seems no issue.

Does this caused by some extra config, like using `UIImageView`, or duing the scroll view (which may trigger a cancel and trigger the SDWebImageWebPCoder instance to dealloc ?)

I guess this crash may be something about the buffer pointer free issue when I call libwebp's API.

**Comment by dreampiggy** [comment]
Although I can not reproduce this issue. I re-visit the Animated WebP implementation. I found that previous version (0.5.0-0.6.0), the implementationi copy the data buffer and does not have any lock on `_demux` instance variable.

The `demux` is the object provided by libwebp, and if the `Update New Progressive Data Buffer` and `Decode the current rendering image` happended at the same time, I doubt there may be some thread safe issue inside libwebp itself. (Though they say thread safe).

So, I create the PR to fix this: See,

1. I use `copy` and release the old demuxer before `_imageData = NULL`, to make sure that libwebp retain the data buffer before we release it. (libwebp don't know about CoreFoundation create rule or get rule, I use the ARC and call order to ensure this).

2. I use lock between the new demuxer creation and the progressive decoding, to avoid potential thread safe issue.

**Comment by JT501** [comment]
Hi, just woke up and tested :)

You got it, the PR fixed the issue, cool !

Thanks

**Comment by dreampiggy** [comment]
@JT501 Actually fix ? So I'll merge and release 0.6.1 version

**Comment by JT501** [comment]
I will do a few more tests to confirm it.

**Comment by JT501** [comment]
After some tests on real device, I can confirm that it did fix the issue.

**Comment by dreampiggy** [comment]
@JT501 Released [v0.6.1](https://github.com/SDWebImage/SDWebImageWebPCoder/releases/tag/0.6.1). Please upgrade and have a try.

**Comment by JT501** [comment]
Good good , thanks a lot
