### ISSUE TITLE
后续是否考虑将直接对libwebp的git依赖改成直接依赖webp.framework

### ISSUE THREAD

**Issue by itdongbaojun** [SDWebImage/SDWebImageWebPCoder#47]
后续是否考虑将直接对libwebp的git依赖改成直接依赖webp.framework
https://developers.google.com/speed/webp/download

**Comment by dreampiggy** [comment]
No possible. Because Google's pre-compied libwebp, does not contains WebPMux(the encoding and animated WebP support).

Ask Google guys to support this at first: https://groups.google.com/a/webmproject.org/g/webp-discuss

**Comment by dreampiggy** [comment]
And. Actually, since Google does not create a CocoaPods dependency, you can actually build your own toolchain .

SDWebImageWebPCoder: folk this, modify podspec and vendor a pre-compiled framework.
or libwebp: change that git repo, to not use source code, instead, pre-compiled framework.

**Comment by itdongbaojun** [comment]
thks, we use the pod libwebp maintained by SDWebImage org
