### ISSUE TITLE
Unable to install via Carthage in Xcode 12

### ISSUE THREAD

**Issue by GOKUXGOD** [SDWebImage/SDWebImageWebPCoder#55]
Here's my cartfle
**github "SDWebImage/SDWebImageWebPCoder" "0.8.3"**

After after looking at the **Carthage error log file** 

The following build commands failed:
- SDWebImageWebPCoderDefine.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
- SDWebImageWebPCoderDefine.m
- SDImageWebPCoder.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
- UIImage+WebP.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
- SDImageWebPCoder.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
- UIImage+WebP.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler

I had a look at this https://github.com/SDWebImage/SDWebImageWebPCoder/issues/44
but its closed 
Please help

**Comment by dreampiggy** [comment]
For Carthage && Xcode 12, be sure you use the way from Carthage official guide: https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md

We have no plan to support XCFramework in short peiord.

Actually, SDWebImage may totally shutdown Carthage support, keeping new Bazel, CocoaPods, SwiftPM only 3 ways.
