### ISSUE TITLE
Declaration of 'SDProgressiveImageCoder' must be imported from module 'SDWebImage' before it is required

### ISSUE THREAD

**Issue by afterxleep** [SDWebImage/SDWebImageWebPCoder#58]
Hello!.  

We are receiving these build errors in XCode 12.5 after setting up the APPLICATION_EXTENSION_API_ONLY flag for the target that uses the library.  (Which is now required to be YES for extensions).

Referenced files are:
- SDWebImageWebPcoder.h

```
/Pods/Headers/Private/SDWebImageWebPCoder/SDImageWebPCoder.h:18:41: error: declaration of 'SDProgressiveImageCoder' must be imported from module 'SDWebImage' before it is required
@interface SDImageWebPCoder : NSObject <SDProgressiveImageCoder, SDAnimatedImageCoder>

```

**Comment by afterxleep** [comment]
Hi Folks, any ideas about this?  Would it be something you would consider fixing?

**Comment by dreampiggy** [comment]
Show the full error log. This `APPLICATION_EXTENSION_API_ONLY` does not effect anything, because the Application Extension API we use only is `UIApplication.shared`. And it's already been checked during runtime.

**Comment by afterxleep** [comment]
It seems the issue was on our side in the end.  Sorry about it.   Closing this one.
