### ISSUE TITLE
[!] Unable to find a specification for `SDWebImageWebPCoder`

### ISSUE THREAD

**Issue by bizibizi** [SDWebImage/SDWebImageWebPCoder#6]

**Comment by kinarob** [comment]
@bpoplauschi @dreampiggy When could we release `SDWebImageWebPCoder`, or could we consider releasing a `SDWebImageWebPCoder` beta first?

**Comment by dreampiggy** [comment]
It's my fault. I assume this already been released and pushed into CocoaPods trunk. I'll release right now.

**Comment by dreampiggy** [comment]
@bizibizi @kinarob It's released. The version 0.1.0. Sorry for this and cause the inconvenient. 😞 

The CocoaPods page: http://cocoapods.org/pods/SDWebImageWebPCoder
The Release page: https://github.com/SDWebImage/SDWebImageWebPCoder/releases/tag/0.1.0

**Comment by kinarob** [comment]
@bizibizi Now, you could have a try!

**Comment by dreampiggy** [comment]
@bizibizi Are you online ? Please help me to review my pending PR https://github.com/SDWebImage/SDWebImage/pull/2558. It's the last one waiting for 4.4.4 release. And I want to merge the master into 5.x and release 5.0.0-beta4 soon. I want to done this today 😅

**Comment by dreampiggy** [comment]
@bizibizi Hi. After I check our SDWebImage 5.0 status. I know the reason. The official SDWebImage 5.0.0-beta4 version, start to ship without WebP subspec. So maybe previouslly some user use the commit or branch dependency for this WebP coder repo. And for that reason, it was not pushed to CocoaPods trunk.

Now, since the [SDWebImage 5.0.0-beta4](https://github.com/SDWebImage/SDWebImage/releases/tag/5.0.0-beta4) released just now. And point the WebP support to this repo. I think the issue can be solved.

Specify the correct version of your Podfile or Cartfile.

```ruby
pod 'SDWebImage', '5.0.0-beta4'
pod 'SDWebImageWebPCoder', '~> 0.1'
```

**Comment by bizibizi** [comment]
okay, it works!
also, have one more questions, i convert images to WebP and I connect this plugin, do i need some other plugin to convert them to HEIF and HEIC?  it always fails with HEIF and HEIC

**Comment by dreampiggy** [comment]
@bizibizi It depends on your use case. Please explain more detail and I can give you solution.

If you means “I have a UIImage from somewhere, I want to encode it to HEIF image data”. Apple’s official encode (we call the default SDImageIOCoder) support it, but with limitation. 

1. Encoding not works on iPhone Simulator.
2. iOS firmware version must be iOS 11+.
3. Only A10 fusion chip and above, supports HEIF encoding. Others only supports HEIF decoding(HEIF image data to UIImage, the opposite way)

**Comment by dreampiggy** [comment]
If you want a more general HEIF encoding / decoding support, without Apple’s limitation and supports iOS 8+. Maybe you should check https://github.com/SDWebImage/SDWebImageHEIFCoder

**Comment by Ekhui** [comment]
> If you want a more general HEIF encoding / decoding support, without Apple’s limitation and supports iOS 8+. Maybe you should check https://github.com/SDWebImage/SDWebImageHEIFCoder

 same problem now , and i run 'pod search SDWebImageWebPCoder'  serached nothings

**Comment by dreampiggy** [comment]
@Ekhui Run `pod repo update`. Or maybe you don't add CocoaPods master repo but using a private forked repo.
