### ISSUE TITLE
In the debug mode APP, the WebPDecode method of libwebp executes very slowly

### ISSUE THREAD

**Issue by yx-mike** [SDWebImage/SDWebImageWebPCoder#60]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 14.5
 SDWebImage Version      | 5.9.3, 0.6.1(SDWebImageWebPCoder), 1.2.0(libwebp)
 Integration Method      | cocoapods
 Xcode Version           | Xcode 12.5
 Repro rate              | 100%
 Repro with our demo prj | Not running yet
 Demo project link       | No
 
 
### Issue Description and Steps

用SDWebImageWebPCoder解码webp图片，发现一个问题。
我用Xcode运行APP，发现在debug模式下，webp解码非常慢，解码耗时大多是好几秒。
但是在release模式下正常，解码很快。

Use SDWebImageWebPCoder to decode webp pictures and found a problem.
I run the app with Xcode and found that in debug mode, webp decoding is very slow, and the decoding time is mostly several seconds.
But it is normal in release mode, and the decoding is very fast.

print time:
![截屏2021-05-28 下午8 13 19](https://user-images.githubusercontent.com/4413224/119982987-22193400-bff2-11eb-88be-e60baec507c7.png)

debug:
![截屏2021-05-28 下午8 13 24](https://user-images.githubusercontent.com/4413224/119982961-19c0f900-bff2-11eb-9637-09f34690c791.png)

release:
![截屏2021-05-28 下午8 16 04](https://user-images.githubusercontent.com/4413224/119982975-1ded1680-bff2-11eb-8996-0216647be9cb.png)

**Comment by 451222664** [comment]
图片尺寸有没区别

**Comment by dreampiggy** [comment]
已知问题。libwebp Google使用pure C实现，在debug mode下会开启一个malloc池，WebPFree和WebPAlloc都会有监控，会影响一部分开销。这部分建议把libwebp打包成二进制来调试（CocoaPods插件有能够提前二进制化的），或者动态修改一下libwebp的podspec，加上-O2和-DNODEBUG=1

**Comment by pepsikirk** [comment]
> 

我看libwebp的podspec也是你上传的，我觉得你可以添加一个subspec，然后加上这些编译参数，并且顺便升级到1.2.3~

**Comment by pepsikirk** [comment]
> 已知问题。libwebp Google使用pure C实现，在debug mode下会开启一个malloc池，WebPFree和WebPAlloc都会有监控，会影响一部分开销。这部分建议把libwebp打包成二进制来调试（CocoaPods插件有能够提前二进制化的），或者动态修改一下libwebp的podspec，加上-O2和-DNODEBUG=1

我看libwebp的podspec也是你上传的，我觉得你可以添加一个subspec，然后加上这些编译参数，并且顺便升级到1.2.3~
我这边改了半天都各种问题，没办法就只能直接google下载framework然后下载SDWebImageWebPCoder源码来集成

**Comment by dreampiggy** [comment]
You can just use CocoaPods-Package gem to pre-build the Pod, and you can change the configruration to releaes.

https://github.com/CocoaPods/cocoapods-packager

This do not need anyone to do extra work.

**Comment by pepsikirk** [comment]
> You can just use CocoaPods-Package gem to pre-build the Pod, and you can change the configruration to release.
> 
> https://github.com/CocoaPods/cocoapods-packager
> 
> Or if you maintain a large dependency tree, you can just use [CocoaPods post-installer script](https://guides.cocoapods.org/syntax/podfile.html), to update only `libwebp` use the Release Configuration or some other compiler options (like `-O3`)
> 
> This do not need anyone to do extra work.

我这边已经通过 post-installer script 集成，确实时间大幅下降了，不过使用 AdHoc 包测试，比直接使用 framework，解码耗时还是会长大概18%左右。
