### ISSUE TITLE
update libwebp dependency to support m1 chip

### ISSUE THREAD

**Issue by hao-feng** [SDWebImage/SDWebImageWebPCoder#62]
libwebp updates to 1.2.1 which supports ARM64 simulator

could u plz update the dependency

**Comment by dreampiggy** [comment]
Actually.

Should move to https://github.com/SDWebImage/libwebp-Xcode

And, libwebp CocoaPods use the source code from google, but not their build script. Currently CocoaPods need to use XCFramework to support ARM64 simulator, which is the main difficult for non-XCFramework user.

**Comment by dreampiggy** [comment]
libwebp source code do support ARM64 M1 target. The only thing should do it's to let CocoaPods automatically handle both XCFramework user and non-XCFramework user.

**Comment by dreampiggy** [comment]
If you compile CocoaPods from source code, actually you can use ARM64 M1 target. Didn't test because I have no M1 Mac...

**Comment by dreampiggy** [comment]
If you're asking Carthage. Sorry I will not maintain any Carthage support. Using SwiftPM or CocoaPods.

**Comment by hao-feng** [comment]
> Actually.
> 
> Should move to https://github.com/SDWebImage/libwebp-Xcode
> 
> And, libwebp CocoaPods use the source code from google, but not their build script. Currently CocoaPods need to use XCFramework to support ARM64 simulator, which is the main difficult for non-XCFramework user.

didn't find this repo before. Thanks, I'll try
