### ISSUE TITLE
Xcode14-beta: Definition of 'CIFilter' must be imported from module 'CoreImage.CIFilter' before it is required

### ISSUE THREAD

**Issue by DwieDave** [SDWebImage/SDWebImageWebPCoder#63]
Hello, 
I've just installed Xcode Beta 14 and I'm getting the following error:

`.../SourcePackages/checkouts/SDWebImage/SDWebImage/Core/SDWebImageIndicator.m:117:26: error build: Definition of 'CIFilter' must be imported from module 'CoreImage.CIFilter' before it is required`

Please see the attached Screenshot:
![sdwebimagewebpcoder-xcode14-error](https://user-images.githubusercontent.com/15933094/172562789-e2543fea-62da-4ec3-877c-b0262ed7d918.jpg)

Info | Value
-- | --
Platform Name | macOS 
Platform Version | 12.4
SDWebImage Version | 5.12.5, 0.8.4(SDWebImageWebPCoder), 1.2.1(libwebp)
Integration Method | SPM
Xcode Version | Xcode 14.0 beta
Demo project link | No

These are all the integrated Packages in my project:
<img width="245" alt="image" src="https://user-images.githubusercontent.com/15933094/172564551-63068a38-e4cc-448e-a358-d76b66dc58a2.png">

Since its still the Beta theres probably not much rush but 
I hope these information will help to future-proof the library.

**Comment by dreampiggy** [comment]
Fixed by upstream SDWebImage 5.12.6+
