### ISSUE TITLE
Possible logic error in scaling  ('encodeMaxPixelSize' option)

### ISSUE THREAD

**Issue by AlexDjr** [SDWebImage/SDWebImageWebPCoder#64]
Hi!
I'm using **SDWebImageWebPCoder** to convert my images to WEBP and have stumbled upon what looks like a logic error in scaling with `encodeMaxPixelSize` option. 

The case looks like this:

- I have an image with size of 1253x403 and I'm trying to scale it to fit in 512x512 size
<img width="601" alt="image" src="https://user-images.githubusercontent.com/34535344/174474277-551c7141-4151-43e2-ab5e-9fc1580510aa.png">

- and it does nothing, the image's size remains 1253x403

- I checked the code and found line 871 in **SDImageWebPCoder**:
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/34535344/174474675-6c74a55f-f4ae-45f0-a907-8fd7d82e9bec.png">

What it says is that **width** and **height** of an image should be **both** larger than respective size values of `encodeMaxPixelSize` option. So in my case I don't meet this condition because my height (403) is smaller than 512.

Shouldn't it be **OR** instead of **AND** in this condition? 
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/34535344/174474980-d13dbebe-2423-4517-badf-f613b75355d4.png">

For my case such fix works correctly: 1253x403 image has been scaled to 512x165 size 

Please guide me if I'm missing something about this logic

**Comment by dreampiggy** [comment]
This logic is wrong, see the similiar PR in SDWebImage Core:

https://github.com/SDWebImage/SDWebImage/pull/3354

I'll fix today with new patch version :)

**Comment by dreampiggy** [comment]
Need to fix SDWebImage Core logic as well...

https://github.com/SDWebImage/SDWebImage/blob/5.12.6/SDWebImage/Core/SDImageIOCoder.m#L255

Actually I can adjust this condition into a function to make its behavior matches across the libraries.

**Comment by dreampiggy** [comment]
Fixed in v0.8.5 and v0.9.0
