### ISSUE TITLE
CoreGraphics

### ISSUE THREAD

**Issue by iDevelopper** [SDWebImage/SDWebImageWebPCoder#74]
WatchOS:

Undefined symbols for all functions from CoreGraphics when install via CocoaPods.

Have to add the framework manually to the pod.

**Comment by dreampiggy** [comment]
I think every watchOS App links CoreGraphics, so it does not explicitly linked. But anyway we can fix this in CocoaPods podspec via 's.frameworks'

**Comment by iDevelopper** [comment]
It is not a watchOS App but a watchOS extension. So you will fix it? Thanks.

Same issue for SDWebImageSVGNativeCoder:
https://github.com/SDWebImage/SDWebImageSVGNativeCoder/issues/5

**Comment by iDevelopper** [comment]
Yes after each pod install or update...

**Comment by dreampiggy** [comment]
Should be also fixed in 0.12.0
