### ISSUE TITLE
Update libwebp version to 1.3.1 or higher

### ISSUE THREAD

**Issue by jehhxuxu** [SDWebImage/SDWebImageWebPCoder#79]
Hi, we found a vulnerability in the libwebp 
https://security.snyk.io/vuln/SNYK-COCOAPODS-LIBWEBP-5489511 

Please can we update to use version 1.3.1 or higher?

**Comment by ygorrrteles** [comment]
up

**Comment by dreampiggy** [comment]
I don't think this repo has any *Hard limit* for libwebp.

Maybe you means https://github.com/SDWebImage/libwebp-Xcode

**Comment by dreampiggy** [comment]
![image](https://github.com/SDWebImage/SDWebImageWebPCoder/assets/6919743/6ac1b4aa-fce7-4878-a977-6e5cf33b4621)

**Comment by jehhxuxu** [comment]
Hmm.. I'm sorry if I misunderstood but we're using a package in flutter https://pub.dev/packages/flutter_image_compress, and that package implements SDWebImageWebPCoder that implements libwebp... and our report shows that SDWebImageWebPCoder is using libwebp 1.2.4
flutter_image_compress@1.0.0 -> SDWebImageWebPCoder@0.11.0 -> libwebp@1.2.4

our podfile.lock

![Screenshot 2023-08-15 at 14 26 04](https://github.com/SDWebImage/SDWebImageWebPCoder/assets/27310692/94c991b6-b0cc-471c-b1cc-322515e72804)

**Comment by dreampiggy** [comment]
> SDWebImageWebPCoder is using libwebp 1.2.4

No, it use the dependency `~> 1.0`, which means all version >= 1.0.0, < 2.0.0 will be used

See: https://github.com/SDWebImage/SDWebImageWebPCoder/blob/master/SDWebImageWebPCoder.podspec#L32

Maybe you just need to update your Podfile, you hardcode the dependency version (your App level, not SDK dependency chain level )
