### ISSUE TITLE
Release Ram

### ISSUE THREAD

**Issue by tanlucvo** [SDWebImage/SDWebImageWebPCoder#80]
Don't release RAM after removeFromSuperview or stopAnimating

**Comment by dreampiggy** [comment]
SDImageCache use `NSCache` which retain your UIImage.

Most cases you can ignore this, if you want immediately free, call `[SDImageCache.memoryCache removeObjectForKey:]` or ``removeAllObjects

**Comment by dreampiggy** [comment]
I think this is usage of SDWebImage , not related to this WebP decoder. See: https://github.com/SDWebImage/SDWebImage/wiki/Common-Problems

**Comment by tanlucvo** [comment]
Thanks you 🚀🚀🚀
