### ISSUE TITLE
Build Error with SDWebImage Version 5.18.0+

### ISSUE THREAD

**Issue by leeari95** [SDWebImage/SDWebImageWebPCoder#84]
Currently, I'm managing project dependencies using Tuist.

Versions:
macOS `13.5.2`
Xcode `14.3.1`
SDWebImage `5.18.2`
SDWebImageWebPCoder `0.13.0`

Build Error Details:

```
Include of non-modular header inside framework module 'SDWebImage': '/Users/AriLee/Developer/MyApp-iOS/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/SDWebImage/SDWebImage/include/SDWebImage/SDWebImageCompat.h'
```

Upon direct testing, I found that the error mentioned above starts occurring from version 5.18.1 of SDWebImage.
By locking the SDWebImage version to 5.18.0, the error no longer arises.

I'm not sure why this error is occurring due to the version difference. Please help.

**Comment by dreampiggy** [comment]
5.18.0 -> 5.18.1

Does not add new header files or source files...The tag diff is here:

The only change is `Package.swift` (SPM manifest file), which I bump the Swift version from 5.0->5.3

**Comment by dreampiggy** [comment]
How tulst works on Swift Package Manager framework ? I have no knowledge about that.

**Comment by dreampiggy** [comment]
Guess this change cause the issue

> // swift-tools-version:5.0
> // swift-tools-version:5.3

But I don't know how the correct way to solve this. SDWebImage itself does not use any non-modular headers ? Always using `#include "Foobar.h"` inside public headers.

**Comment by rishabh876** [comment]
Any update here?
I am looking for a specific fix in version 5.18.1 due to which [images are showing upside down](https://github.com/SDWebImage/SDWebImage/pull/3597).

**Comment by dreampiggy** [comment]
I didn't see any error in SDWebImage's standard unit test on integration.

If you face issue, provide the reproduce demo 

## Not a sample code, I means, the total reproducable demo, a zip archive or git repo is OK

**Comment by dreampiggy** [comment]
Here is my test Demo, using Swift PM

[SDWebImageSwiftPMObjc.zip](https://github.com/SDWebImage/SDWebImageWebPCoder/files/13415007/SDWebImageSwiftPMObjc.zip)

I didn't find anything integration issue.

<img width="267" alt="截屏2023-11-20 20 55 36" src="https://github.com/SDWebImage/SDWebImageWebPCoder/assets/6919743/5c0a4fc1-4cf5-4ec4-a33d-26519e38ac51">


Xcode 14.3.1

**Comment by rishabh876** [comment]
Ok it looks like I am also using 5.18.5 but still the images are getting upside down while encoding. 
It can be reproduce 
- Use Simulator with iOS 17.0 and pick the sample image in Simulator with the pink flowers. https://imgur.com/a/3WdWtZU
- Encode image`SDImageWebPCoder.shared.encodedData(with: image, format: .webP, options: [.encodeCompressionQuality: 0.8, .encodeMaxFileSize: 1024 * 1024])`
- The produced image comes upside down

**Comment by dreampiggy** [comment]
That fix is for JPEG only, not the WebP encoding. Maybe new bugs

**Comment by dreampiggy** [comment]
Can you create a new issue instead ? So I can create PR directly point to that. This PR seems out of data and related

**Comment by dreampiggy** [comment]
@rishabh876 Create a new issue with your demo ? I can not reproduce with the description you say.

For example 

1. I don't know how you say `https://imgur.com/a/3WdWtZU`, this is an PNG image, no EXIF orientation which effect the image orientation. And my encoding result to webp works great. You can provide the input image (to be encoded) zip archive to me

**Comment by dreampiggy** [comment]
The build issue no long exists and close
