### ISSUE TITLE
iOS 11兼容性问题

### ISSUE THREAD

**Issue by hao-feng** [SDWebImage/SDWebImageWebPCoder#86]
iOS 11.3
Xcode 15
libwebp 1.3.2

在这里会报错，导致iOS 11设备无法正常加载webp图片。
https://github.com/SDWebImage/SDWebImageWebPCoder/commit/81969472d3581c2b9c5cb38ec660c6953b34bc30#diff-e9c046b25a4d1b5fd2e490c2ebc802f1a63ef0459e0ad74dd3647f72d9c68323R638
Unsupported libwebp preferred CGBitmapInfo: 4357

**Comment by dreampiggy** [comment]
Have a try with SDWebImageWebPCoder 0.14.0, I'm sure this is a old version issue.

**Comment by hao-feng** [comment]
The bug introduced in 0.13.0, and we can still reproduce it in 0.14.0

**Comment by dreampiggy** [comment]
? I think this is similiar to https://github.com/SDWebImage/SDWebImage/pull/3334

Do you means "Only contains issue on iOS 11, no issue on iOS 12" ?

**Comment by dreampiggy** [comment]
Seems Apple old version does not supports the new version's CGImage bitmap combination...Suck

**Comment by dreampiggy** [comment]
Please provide the runtime return value of `[SDImageCoderHelper preferredBitmapInfo:hasAlpha]`. I check whether libwebp can nativally support this format


If not, we can add a backup logic, which use `CGBitmapContext` to draw canvas and CGContextDrawImage on it with RGBA8888 libwebp CGImage

**Comment by dreampiggy** [comment]
![image](https://github.com/SDWebImage/SDWebImageWebPCoder/assets/6919743/b087fb6b-b34b-4020-a2ba-961be12ca38b)

Do like this (on your iPhone OS 11 device)

**Comment by hao-feng** [comment]
(lldb) po cgImage
<CGImage 0x1c43c0c30>
	<<CGColorSpace 0x1c40ac9c0> (kCGColorSpaceICCBased; kCGColorSpaceModelRGB; sRGB IEC61966-2.1; extended range)>
		width = 1, height = 1, bpc = 16, bpp = 64, row bytes = 32 
		kCGImageAlphaNoneSkipLast | kCGImageByteOrder16Little | kCGBitmapFloatComponents 
		is mask? No, has mask? No, has matte? No, should interpolate? Yes

**Comment by dreampiggy** [comment]
The `kCGImageByteOrder16Little | kCGBitmapFloatComponents` is 16bit RGBA16161616, for HDR image and 2x bigger (RAM occupy) than normal non-HRD images

Which SDWebImage does not supported yet.

See feature requests https://github.com/SDWebImage/SDWebImage/issues/3553

**Comment by dreampiggy** [comment]
The better quick workaround is to limit the `[SDImageCoderHelper preferredBitmapInfo:hasAlpha]` to always return non-HDR images (at least for now)

Or, I update the SDWebImageWebPCoder logic here to ignore HDR image. Because even the decoder product the 16 bit CGImage, on SDWebImage there are logic which strip the HRD away and consume only 8 bit CGImage, which still waste the work decoder done.

**Comment by dreampiggy** [comment]
I guess this is Apple's internal changes behavior. The old version `UIGraphicsImageRenderer` internally use 16 bit on iOS 11, but revert this behavior on iOS 12.

**Comment by dreampiggy** [comment]
Decide to quick hack to treat this 16 bits as 8 Bits instead. :(

And I totally aggree SDWebImage itself should provide some HDR control, because actually WebP (legacy) does not supports HDR at all, and no need to produce 16 bit CGImage. It should always produce 8 bit CGImage

**Comment by hao-feng** [comment]
> Decide to quick hack to treat this 16 bits as 8 Bits instead. :(
> 
> And I totally aggree SDWebImage itself should provide some HDR control, because actually WebP (legacy) does not supports HDR at all, and no need to produce 16 bit CGImage. It should always produce 8 bit CGImage

Great, after you have a fix, I'm happy to test again

**Comment by dreampiggy** [comment]
@hao-feng Test now

**Comment by hao-feng** [comment]
pod 'SDWebImageWebPCoder',  :git => '[github.com/SDWebImage/SDWebImageWebPCoder.git](http://github.com/SDWebImage/SDWebImageWebPCoder.git)', :commit => 'eeebf2137e96db6211b909891c67112697b9421c'

the imageRef is nil after this 
https://github.com/SDWebImage/SDWebImageWebPCoder/pull/87/files#diff-e9c046b25a4d1b5fd2e490c2ebc802f1a63ef0459e0ad74dd3647f72d9c68323R679

**Comment by hao-feng** [comment]
> Typo. The `bitmapInfo` create a empty enum and not override the outer one.
> 
> @hao-feng Use new commits [74164f9](https://github.com/SDWebImage/SDWebImageWebPCoder/commit/74164f917ffcd44396b961a28b05d69e2a510723)

This fix works~

**Comment by hao-feng** [comment]
yes, please

**Comment by dreampiggy** [comment]
0.14.1 available
