### ISSUE TITLE
Image is upside down after webp compression

### ISSUE THREAD

**Issue by rishabh876** [SDWebImage/SDWebImageWebPCoder#91]
Following attached image from iPhone simulator is getting upside down after webp compression. I am using 0.14.2 version of SDWebImageWebPCoder. 
Phone: iPhone 15
OS: 17.0

Code 

```
func compressImageData(data: Data)-> Data? {
        let image = UIImage(data: data)
        let lossyWebpData = SDImageWebPCoder.shared.encodedData(with: image, format: .webP, options: [.encodeCompressionQuality: 0.8, .encodeMaxFileSize: 1024 * 1024])
        return lossyWebpData
    }
```

[IMG_0006.HEIC.zip](https://github.com/SDWebImage/SDWebImageWebPCoder/files/13425405/IMG_0006.HEIC.zip)

**Comment by dreampiggy** [comment]
Need more information to test. Seems the decoding part, not encoding part issue

**Comment by dreampiggy** [comment]
OK. Seems our webp coder does not handle the EXIF orientation for **encoding**

Only handle the EXIF orientation for **decoding**😂

<img width="903" alt="截屏2024-02-04 17 51 41" src="https://github.com/SDWebImage/SDWebImageWebPCoder/assets/6919743/d5d6c1eb-48fe-4616-9b77-2ce505247f73">
