### ISSUE TITLE
One of the two will be used. Which one is undefined.

### ISSUE THREAD

**Issue by Jetsond** [SDWebImage/SDWebImageWebPCoder#92]
![image](https://github.com/SDWebImage/SDWebImageWebPCoder/assets/15120827/8d40fb38-3d81-4a59-b514-0beddd9a7e57)
![image](https://github.com/SDWebImage/SDWebImageWebPCoder/assets/15120827/0de2dd41-9084-457b-a769-270b72973827)

**Comment by dreampiggy** [comment]
I guess this is your bug. Or you use a modified cocoapods 

This `~> 5.17` matches 5.18.7 semversion

**Comment by Jetsond** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
