### ISSUE TITLE
Adding Apple Privacy Manifest to SDWebImageWebPCoder

### ISSUE THREAD

**Issue by FilDevTronic** [SDWebImage/SDWebImageWebPCoder#93]
Hello,

I noticed that the main SDWebImage library now includes an Apple Privacy Manifest ([Issue #3550](https://github.com/SDWebImage/SDWebImage/issues/3550)), which is great for meeting Apple's new SDK requirements ([Apple Third-Party SDK Requirements](https://developer.apple.com/support/third-party-SDK-requirements/)). I'm curious if there are plans to implement a similar update for SDWebImageWebPCoder?

**Comment by dreampiggy** [comment]
I don't think other SDK like coders plugin need this.

They don't access anything outside of the coder API call
