### ISSUE TITLE
build failed after 0.14.4 release

### ISSUE THREAD

**Issue by piggy-park** [SDWebImage/SDWebImageWebPCoder#97]
After update version to 0.14.4, i can't build with this error.
i think it's related with this [issue](https://github.com/SDWebImage/SDWebImage/issues/2774).
Even though i read that issue, i still can't come up with any workaround.
it there any update for this issue?

<img width="1589" alt="스크린샷 2024-02-05 오후 4 46 54" src="https://github.com/SDWebImage/SDWebImageWebPCoder/assets/111336385/20f4367e-271a-41c5-9aa7-36913479b3b3">

**Comment by pepsikirk** [comment]
I have the same problem. I opened generate_multiple_pod_projects on Cocoapods.

**Comment by dreampiggy** [comment]
Seems....That `internal macro` header, is private header on SPM

But public header in CocoaPods :)

Will provide a quick fix, by `copy the internal macro` into this WebP coder :0
